config/routes.rb
Rails.application.routes.draw do
  resources :collections
  get 'artists/index'
  get 'artists/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '*path', to: 'home#index', constraints: ->(request){ request.format.html? }
  root to: 'home#index'
  get '/artists', to: 'artists#index'
  get '/artists/:id', to:'artists#show', as: 'artist'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :collections
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
@client_id = ENV['SPOTIFY_CLIENT_ID']
@client_secret = ENV['SPOTIFY_CLIENT_SECRET']
RSpotify::authenticate(@client_id, @client_secret)

class ArtistsController < ApplicationController
  def index
    if !params[:artist_name].empty?
      @artists = RSpotify::Artist.search(params[:artist_name])
    else
      redirect_to root_path
    end
  end

  def show
    @artist = RSpotify::Artist.find(params[:id])
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  # before_action :set_collection, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  def index
    @collections = current_user.collections.order(created_at: :desc)
      # render json: @collections
  end

  def show
    @collection = Collection.find(params[:id])
  end

  def new
    @collection = current_user.Collection.new
  end

  def create
    @collection = current_user.collections.new(collection_params)
    respond_to do |format|
      if @collection.save
          format.html { redirect_to @collection, notice: 'Album has been saved to collection.' }
          format.json { render :show, status: :created, location: @collection }
      else
          format.html { render :new }
          format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @collection = Collection.find(params[:id])
  end

  def update
    @collection = Collection.find(params[:id])
    if @collection.update_attributes(collection_params)   
      flash[:notice] = 'Collection updated!'   
      redirect_to root_path   
    else   
      flash[:error] = 'Failed to edit collection!'   
      render :edit   
    end   
  end   

  def destroy
    @collection = Collection.find(params[:id])
    if @collection.delete
      flash[:notice] = 'Collection deleted'
      redirect_to root_path
    else
      flash[:error] = 'Failed to delete this collection!'   
      render :destroy 
    end  
  end 

  private
  
  #use strong parameters for the validation of params
  def collection_params
      params.require(:collection).permit(:album_name, :artist_name, :comment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/artists/index.html.erb
<div class="container">
    <h1 class="page-header">Artists Matching "<%= params[:artist_name] %>"</h1>
    <ul>
    <% @artists.each do |artist| %>
    <li id="show_btn"><%= artist.name %> | <%= link_to "Show", artist_path(artist.id) %></li>
    <% end %>
    </ul>
</div>

app/views/artists/show.html.erb
<div class="container">
  <h1 class="page-header"><%= @artist.name %></h1>
  <% @artist.albums(limit:5).each do |album| %>
    <Button class="save_btn">Save</Button>
    <h3><%= album.name %></h3>
    <h5>popularity: <%= album.popularity %></h5>
    <ol>
      <% album.tracks.each do |track| %>
        <%# <%= album.images[0].url %> 
        <li>
          <%= track.name %>
        </li>
      <% end %>
    </ol>
  <% end %>
</div>

app/views/collection/index.html.erb
<nav class="nav-bar">
  <a class="logo" href="/"><img src="/assets/sandcamp_logo.svg"/></a>

 <div class="search-bar">
    <%= form_tag artists_path, method: "get", html: { class: "form" } do %>
    <div class="form-group col-xs-4 ">
      <%= text_field_tag(:artist_name, "", placeholder: "Enter artist name", class: "form-control") %>
      <%= submit_tag " ", class: "btn search-btn" %>
    </div>
    <%# <div class="dropdown-contents">
        <a class="dropdown-content" style="background-color:#F69C59;" href="https://bandcamp.com/tag/electronic">electronic <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#F3684C;" href="https://bandcamp.com/tag/metal/">metal <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#DA222F;" href="https://bandcamp.com/tag/rock/">rock <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#CE2F62;" href="https://bandcamp.com/tag/alternative/">alternative <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#B93698;" href="https://bandcamp.com/tag/hip-hop/rap/">hip-hop/rap <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#9157B8;" href="https://bandcamp.com/tag/experimental/">experimental <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#7667A8;" href="https://bandcamp.com/tag/punk/">punk <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#7B85C4;" href="https://bandcamp.com/tag/pop/">pop <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#7C9EBD;" href="https://bandcamp.com/tag/ambient/">ambient <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#2D2D2D;" href="https://bandcamp.com/?t=undefined&g=all#discover">browse all <i class="arrow right"></i></a>
    </div> %>
    <% end %>
  </div>

  <div id="user-nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.<br/>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "My Collection", collection_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :get, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div>
</nav>

<p>Collection</p>

<div id="collection-section">
        
</div>

app/views/collections/index.html.erb
<nav class="nav-bar">
  <a class="logo" href="/"><img src="/assets/sandcamp_logo.svg"/></a>

 <div class="search-bar">
    <%= form_tag artists_path, method: "get", html: { class: "form" } do %>
    <div class="form-group col-xs-4 ">
      <%= text_field_tag(:artist_name, "", placeholder: "Enter artist name", class: "form-control") %>
      <%= submit_tag " ", class: "btn search-btn" %>
    </div>
    <% end %>
  </div>

  <div id="user-nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.<br/>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "My Collection", collections_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :get, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div>
</nav>

<p><b>My Collections</b></p>

<div id="collection-section">
  <% for album in @collections%>
    <div class="collection">
      <b> <%= album.album_name %> </b>
      <br/>
      by <%= album.artist_name %>
      <br/>
      <p id="show_btn"> <%= link_to "Show", collection_path(album.id) %> </p>
    </div>
  <% end %>
</div>

app/views/collections/show.html.erb
<div class="container">
    <h1><%= @collection.album_name %> by <%= @collection.artist_name %></h1>
    <p>Comments: <%= @collection.comment %></p>
</div>

app/views/home/index.html.erb
<nav class="nav-bar">
  <a class="logo" href="/"><img src="/assets/sandcamp_logo.svg"/></a>

 <div class="search-bar">
    <%= form_tag artists_path, method: "get", html: { class: "form" } do %>
    <div class="form-group col-xs-4 ">
      <%= text_field_tag(:artist_name, "", placeholder: "Enter artist name", class: "form-control") %>
      <%= submit_tag " ", class: "btn search-btn" %>
    </div>
    <%# <div class="dropdown-contents">
        <a class="dropdown-content" style="background-color:#F69C59;" href="https://bandcamp.com/tag/electronic">electronic <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#F3684C;" href="https://bandcamp.com/tag/metal/">metal <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#DA222F;" href="https://bandcamp.com/tag/rock/">rock <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#CE2F62;" href="https://bandcamp.com/tag/alternative/">alternative <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#B93698;" href="https://bandcamp.com/tag/hip-hop/rap/">hip-hop/rap <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#9157B8;" href="https://bandcamp.com/tag/experimental/">experimental <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#7667A8;" href="https://bandcamp.com/tag/punk/">punk <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#7B85C4;" href="https://bandcamp.com/tag/pop/">pop <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#7C9EBD;" href="https://bandcamp.com/tag/ambient/">ambient <i class="arrow right"></i></a>
        <a class="dropdown-content" style="background-color:#2D2D2D;" href="https://bandcamp.com/?t=undefined&g=all#discover">browse all <i class="arrow right"></i></a>
    </div> %>
    <% end %>
  </div>

  <div id="user-nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.<br/>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "My Collection", collections_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :get, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div>


</nav>



<p>Dig and discover hidden gems in the sand-like music world.</p>

  <div id="intro-section">
        
  <div class="img-container">
     
  </div>
  <div class="second-col">
     
  </div>
</div> 
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SandcampNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>